discord:
  bot:
    token: ODcwMDUxNzMyNjI4MDc4NjYy.G3-Lxr.rHCTdX_Bvw9JYeYtB4ZQgMv-B6yO3NMCSnxQd4
  server:
    channels:
      statistics:
        members: null
        voice: null
      door: null  # welcome channel
      create_voice: null